### ISSUE TITLE
additionalProperties

### ISSUE THREAD

**Issue by the4thamigo-uk** [a-h/generate#23]
I have a schema that allows for additionalProperties of a given type. I think that each entry in the additionalProperties list should translate to a map[string]*MyType member in the struct. If there are multiple allowed types there should be a similar struct member for each one. (Im not sure how you would name each datamember though)?

Would you accept a PR for this feature?

**Comment by a-h** [comment]
From the spec, `additionalProperties` in JSON schema can be a boolean or a JSON schema object.

In the case it is a boolean, if it's set to false, then no change. In the case that it's set to true, then any number of additional properties can be added to the object. I don't think there's a way to describe this in Go except perhaps for a field of `AdditionalProperties map[string]interface{}`.

It's been a while since I looked at this - I don't know how JSON unmarshal would work out to dump the additional properties that aren't fields into the `AddtionalProperties` field.

In the case that `additionalProperties` is schema like:

```js
"additionalProperties": { "type": "MyType" }
```

Then adding a field of `AdditionalProperties map[string]*MyType` would make sense, but since `additionalProperties` is JSON schema, there's lots of other rules that can be applied to, so I'd like to see those edge cases considered in a PR too.

But, yeah, I'd definitely take a pull request. Thanks!

**Comment by the4thamigo-uk** [comment]
I agree it is hard to do this to cater for all JSON schema rules. i.e. supporting oneOf, anyOf etc would be overkill I think. Although it is a gross simplification, I think the main use case is where you have a single object type in additionalProperties and nothing defined in properties. This allows you to have a map of objects in the json that would convert to a map[string]*MyType in the golang.

```
"some_object": {
		"description": "some object that we will convert to a golang struct 'SomeObject'",
		"type": "object ",
		"properties": {
			"map_field": {
				"description": "a map of objects that we will convert to a member 'MapField map[string]*MapFieldAdditional' in 'SomeObject'",
				"type": "object ",
				"additionalProperties": {
					"type": "object",
					"properties": {
						"x": {
							"description": "some value that will be a member 'X int' of struct 'MapFieldAdditional'",
							"type": "integer"
						}
					}
				}
			}
		}
	}
```

**Comment by the4thamigo-uk** [comment]
Ive committed a tentative fix for this in my repo. It doesnt have tests yet, but please feel free to comment on the approach.

**Comment by the4thamigo-uk** [comment]
Ive updated the code so that it copes with any use of `anyOf`, `oneOf` or `allOf`. However, it currently only generates a map if there is a total of exactly one schema within any of these sections.
