### ISSUE TITLE
Nested schemas like "$ref": "uuid.json"

### ISSUE THREAD

**Issue by wizpnz** [a-h/generate#9]
Hi, awesome work!
Seems, like it has lack of $ref to external schemas support.

**Comment by a-h** [comment]
Hey there, thanks! Yes, it doesn't currently support that, sorry!

I didn't need it for the work I was doing and introducing it is fairly complex because you then have to deal with resolution of the external schemas by looking at filesystem or pulling them from the Web.

If you pull from the file system, relative to where? If you pull from the Web, which domains do you trust? How many connections do you allow? What happens with a timeout / other error? What if a schema you import has a link to another schema? How deep do you go? How many redirects do you follow etc.? Where do you put the schema that you've previously downloaded? Do you cache them? Not insurmountable problems, just needs a bit of thought. 😁 

I was thinking the best way might be to pass in a "resolver" that has the rules in it for acquiring and caching various external schema.

I'm a bit stacked at the moment with work for clients, but I'd be happy to take in / work on a pull request. 😁
